# 微博账号
WEIBO_USERNAME = '1XXXXXXX6'
# 微博密码
WEIBO_PASSWORD = 'xXXXXXXXXXXXXXXXXxx'
# 若快账号
RUOKUAI_USERNAME = 'XXXXXXXXX'
# 若快密码
RUOKUAI_PASSWORD = 'XXXXXXXXXXXXX'
# 是否自动打码
IS_AUTOMATIC_CODE = False
